# workaround for buffer overflow issue, ref https://github.com/travis-ci/travis-ci/issues/5227
addons:
  hosts:
    - myshorthost
  hostname: myshorthost

language: java
jdk:
  - oraclejdk8
  - openjdk7